"""SQL DDL exporter for database schemas."""

from pathlib import Path
from typing import Any


class SQLExporter:
    """Export database schemas to SQL DDL format."""

    def __init__(self, output_dir: str | Path):
        """
        Initialize the SQL exporter.

        Args:
            output_dir: Directory to write output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export(
        self,
        db_schemas: list[dict[str, Any]],
        filename: str = "schema.sql",
        dialect: str = "postgresql",
    ) -> Path:
        """
        Export database schemas to SQL DDL.

        Args:
            db_schemas: List of database schema dictionaries
            filename: Output filename
            dialect: SQL dialect (postgresql, mysql)

        Returns:
            Path to the generated file
        """
        ddl = self._generate_ddl(db_schemas, dialect)

        file_path = self.output_dir / filename
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(ddl)

        return file_path

    def _generate_ddl(
        self,
        schemas: list[dict[str, Any]],
        dialect: str,
    ) -> str:
        """Generate DDL statements for all schemas."""
        lines = [
            "-- Auto-generated Database Schema",
            f"-- Dialect: {dialect.upper()}",
            "-- Generated by doc-pipeline",
            "",
        ]

        for schema in schemas:
            lines.append(self._generate_table_ddl(schema, dialect))
            lines.append("")

        # Add indexes
        for schema in schemas:
            for index in schema.get("indexes", []):
                lines.append(self._generate_index_ddl(schema["name"], index))

        return "\n".join(lines)

    def _generate_table_ddl(
        self,
        schema: dict[str, Any],
        dialect: str,
    ) -> str:
        """Generate CREATE TABLE statement."""
        table_name = schema.get("name", "table")
        description = schema.get("description", "")

        lines = []

        # Add comment
        if description:
            lines.append(f"-- {description}")

        lines.append(f"CREATE TABLE IF NOT EXISTS {table_name} (")

        # Columns
        column_defs = []
        primary_keys = []

        for col in schema.get("columns", []):
            col_def = self._generate_column_def(col, dialect)
            column_defs.append(f"    {col_def}")

            if col.get("primary_key"):
                primary_keys.append(col["name"])

        # Add primary key constraint if not inline
        if len(primary_keys) > 1:
            pk_cols = ", ".join(primary_keys)
            column_defs.append(f"    PRIMARY KEY ({pk_cols})")

        # Add constraints
        for constraint in schema.get("constraints", []):
            constraint_def = self._generate_constraint_def(constraint)
            if constraint_def:
                column_defs.append(f"    {constraint_def}")

        lines.append(",\n".join(column_defs))
        lines.append(");")

        return "\n".join(lines)

    def _generate_column_def(
        self,
        col: dict[str, Any],
        dialect: str,
    ) -> str:
        """Generate column definition."""
        name = col.get("name", "column")
        col_type = self._normalize_type(col.get("type", "TEXT"), dialect)

        parts = [name, col_type]

        # Primary key (single column)
        if col.get("primary_key"):
            parts.append("PRIMARY KEY")

        # Nullable
        if col.get("nullable") is False:
            parts.append("NOT NULL")

        # Unique
        if col.get("unique"):
            parts.append("UNIQUE")

        # Default value
        default = col.get("default")
        if default is not None:
            parts.append(f"DEFAULT {default}")

        # On update (for timestamps)
        if col.get("on_update"):
            if dialect == "postgresql":
                # PostgreSQL needs a trigger for ON UPDATE
                pass
            else:
                parts.append(f"ON UPDATE {col['on_update']}")

        return " ".join(parts)

    def _normalize_type(self, type_str: str, dialect: str) -> str:
        """Normalize type string for dialect."""
        type_upper = type_str.upper()

        # PostgreSQL specific mappings
        if dialect == "postgresql":
            mappings = {
                "DATETIME": "TIMESTAMP",
                "INT": "INTEGER",
                "BOOL": "BOOLEAN",
            }
            for old, new in mappings.items():
                type_upper = type_upper.replace(old, new)

        return type_upper

    def _generate_index_ddl(
        self,
        table_name: str,
        index: dict[str, Any],
    ) -> str:
        """Generate CREATE INDEX statement."""
        index_name = index.get("name", f"idx_{table_name}")
        columns = ", ".join(index.get("columns", []))
        unique = "UNIQUE " if index.get("unique") else ""

        return f"CREATE {unique}INDEX IF NOT EXISTS {index_name} ON {table_name} ({columns});"

    def _generate_constraint_def(self, constraint: dict[str, Any]) -> str | None:
        """Generate constraint definition."""
        constraint_type = constraint.get("type", "")
        name = constraint.get("name", "constraint")

        if constraint_type == "check":
            expression = constraint.get("expression", "")
            return f"CONSTRAINT {name} CHECK ({expression})"
        elif constraint_type == "foreign_key":
            columns = constraint.get("columns", [])
            ref_table = constraint.get("references_table", "")
            ref_columns = constraint.get("references_columns", [])
            return (
                f"CONSTRAINT {name} FOREIGN KEY ({', '.join(columns)}) "
                f"REFERENCES {ref_table} ({', '.join(ref_columns)})"
            )

        return None
